//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CokEglencez.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-0QVMQPL\\SQLEXPRESS;Initial Catalog=Stok;Integrated Security=T" +
            "rue")]
        public string StokConnectionString {
            get {
                return ((string)(this["StokConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YG0234-22-01\\SQLEXPRESS;Initial Catalog=Stok;Integrated Security=True" +
            "")]
        public string StokConnectionString1 {
            get {
                return ((string)(this["StokConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YG0234-22-01\\SQLEXPRESS;Initial Catalog=Stok2;Integrated Security=Tru" +
            "e")]
        public string Stok2ConnectionString {
            get {
                return ((string)(this["Stok2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YG0234-22-01\\SQLEXPRESS;Initial Catalog=stok3;Integrated Security=Tru" +
            "e")]
        public string stok3ConnectionString {
            get {
                return ((string)(this["stok3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YG0234-22-01\\SQLEXPRESS;Initial Catalog=Stok4;Integrated Security=Tru" +
            "e")]
        public string Stok4ConnectionString {
            get {
                return ((string)(this["Stok4ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YG0234-22-01\\SQLEXPRESS;Initial Catalog=stok5;Integrated Security=Tru" +
            "e")]
        public string stok5ConnectionString {
            get {
                return ((string)(this["stok5ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YG0234-22-01\\SQLEXPRESS;Initial Catalog=stokSon;Integrated Security=T" +
            "rue")]
        public string stokSonConnectionString {
            get {
                return ((string)(this["stokSonConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-0QVMQPL\\SQLEXPRESS;Initial Catalog=yeni;Integrated Security=T" +
            "rue")]
        public string yeniConnectionString {
            get {
                return ((string)(this["yeniConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-0QVMQPL\\SQLEXPRESS;Initial Catalog=yenicik;Integrated Securit" +
            "y=True")]
        public string yenicikConnectionString {
            get {
                return ((string)(this["yenicikConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-0QVMQPL\\SQLEXPRESS;Initial Catalog=deneme111;Integrated Secur" +
            "ity=True")]
        public string deneme111ConnectionString {
            get {
                return ((string)(this["deneme111ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YG0234-22-01\\SQLEXPRESS;Initial Catalog=Deneme1;Integrated Security=T" +
            "rue")]
        public string Deneme1ConnectionString {
            get {
                return ((string)(this["Deneme1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YG0234-22-01\\SQLEXPRESS;Initial Catalog=deneme2;Integrated Security=T" +
            "rue")]
        public string deneme2ConnectionString {
            get {
                return ((string)(this["deneme2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YG0234-22-01\\SQLEXPRESS;Initial Catalog=deneme3;Integrated Security=T" +
            "rue")]
        public string deneme3ConnectionString {
            get {
                return ((string)(this["deneme3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YG0234-22-01\\SQLEXPRESS;Initial Catalog=deneme4;Integrated Security=T" +
            "rue")]
        public string deneme4ConnectionString {
            get {
                return ((string)(this["deneme4ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-0QVMQPL\\SQLEXPRESS;Initial Catalog=v1stok;Integrated Security" +
            "=True")]
        public string v1stokConnectionString {
            get {
                return ((string)(this["v1stokConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-0QVMQPL\\SQLEXPRESS;Initial Catalog=v2Stok;Integrated Security" +
            "=True")]
        public string v2StokConnectionString {
            get {
                return ((string)(this["v2StokConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-0QVMQPL\\SQLEXPRESS;Initial Catalog=stok3v3;Integrated Securit" +
            "y=True")]
        public string stok3v3ConnectionString {
            get {
                return ((string)(this["stok3v3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YG0234-22-01\\SQLEXPRESS;Initial Catalog=stokV1;Integrated Security=Tr" +
            "ue")]
        public string stokV1ConnectionString {
            get {
                return ((string)(this["stokV1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-0QVMQPL\\SQLEXPRESS;Initial Catalog=STOKSON;Integrated Securit" +
            "y=True")]
        public string STOKSONConnectionString1 {
            get {
                return ((string)(this["STOKSONConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YG0234-22-01\\SQLEXPRESS;Initial Catalog=stokv3;Integrated Security=Tr" +
            "ue")]
        public string stokv3ConnectionString {
            get {
                return ((string)(this["stokv3ConnectionString"]));
            }
        }
    }
}
